language:
    python

  python:
    - "3.5"

  cache:
    pip

  install:
    - pip install -r requirements.txt

  before_script:
  - pip install coverage
  - pip install coveralls
  - pip install codecov

  script:
    - python test_jaxifier.py
    - coverage run test_jaxifier.py

  after_success:
  - codecov